import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/navbar";
import { BodyPage } from "../styles/pageStyle/_Home";

const Home: NextPage = () => {
  return (
    <>
      <BodyPage>
        <Head>
          <title>MKS Sistemas</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
      </BodyPage>
    </>
  );
};

export default Home;
